/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RecordRecordIdImport } from './routes/record.$recordId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecordRecordIdRoute = RecordRecordIdImport.update({
  id: '/record/$recordId',
  path: '/record/$recordId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/record/$recordId': {
      id: '/record/$recordId'
      path: '/record/$recordId'
      fullPath: '/record/$recordId'
      preLoaderRoute: typeof RecordRecordIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/record/$recordId': typeof RecordRecordIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/record/$recordId': typeof RecordRecordIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/record/$recordId': typeof RecordRecordIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/record/$recordId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/record/$recordId'
  id: '__root__' | '/' | '/record/$recordId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecordRecordIdRoute: typeof RecordRecordIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecordRecordIdRoute: RecordRecordIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/record/$recordId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/record/$recordId": {
      "filePath": "record.$recordId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
